include ../core.mk

MAKEFLAGS += --no-print-directory

## test=true Test Flag Root
TEST_FLAG_ROOT ?= test-flag-root

TEST_FLAG_ROOT_NO_HELP ?=

## test=true Test included root
test-root:

test-root-no-help:
