#!/usr/bin/env bash

# Stop when errors
set -e

# Default directories
SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR/.."
ROOT_DIR=$(pwd)

# include test framework
. "$ROOT_DIR/script/assert.sh"

cd "$ROOT_DIR/test"
assert "make --makefile Makefile.test test-included" 'test-included-done'
assert_raises "make --makefile Makefile.test self-update" 0
assert_end
